### ISSUE TITLE
Pressing Enter in search box replaces search with "undefined"

### ISSUE THREAD

**Issue by bashenk** [TimIsOverpowered/MOONMOON-Frontend#13]
Pressing Enter in the search form fails and replaces the entire search text with "undefined".

Tested in Firefox 122.0 and Edge 121.0.2277.83. Attempting to run in a private window or disabling add-ons neither do change this behavior.

Possibly unrelated, but in Firefox, clicking into the Search box produces the following console warning:
`Empty string passed to getElementById().` from source [896.2ffb7ca7.chunk.js:1:5545](https://moon2.tv/static/js/896.2ffb7ca7.chunk.js).

**Comment by TimIsOverpowered** [comment]
Replaced Search

**Comment by chrsmmns** [comment]
Yo @TimIsOverpowered just wanted to let you know your updated filter & search is awesome, absolutely love it. moon2CUTE
