### ISSUE TITLE
some emotes don't show up

### ISSUE THREAD

**Issue by MOON2NICE** [TimIsOverpowered/MOONMOON-Frontend#3]
some emotes don't show up such as "Reallygun" "BillyApprove" "forsenPls" "RareParrot" and "Stare" , if all emotes could show up , that will make me really happy , thank you 
if possible i wish if you can hover your mouse over an emote and preview it (like in twitch) thank you so much

**Comment by TimIsOverpowered** [comment]
It should be showing up. If you can point me to a timestamp of a vod where you encountered it not working, it would help me.

**Comment by TimIsOverpowered** [comment]
emote tooltips added per https://github.com/TimIsOverpowered/MOONMOON-Frontend/commit/187e3f0adc008e3f2909c15bfb4ddfeac4cc24b7

**Comment by DaveYognaught** [comment]
Think I may have encountered the same issue as this guy so want to provide more info. 

If you check the Inspector in DevTools (I use Firefox) you should get an error each time the emote fails to load. 
From what i've seen so far, it's:

"Stare", "cumBo", "Clap", "GoodTake", "Tomfoolery", "Ez"

Each error is like so, seems to be almost entirely with 7tv, but some 7tv emotes like "NONTARGET" load fine:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://emotes.overpowered.tv/7tv/62fc0a0c4a75fd54bd3520a9/2x.webp. (Reason: CORS header 'Access-Control-Allow-Origin' does not match '*, https://moon2.tv'/).

Link to vod:

https://moon2.tv/youtube/1794804906

Part 1, 37:10
Moon tells chat to applause, lots of "Clap" gets posted but in the chat it just looks like an empty message and nothing was posted.
