### ISSUE TITLE
Increase "Chat Paused" tolerance to allow large copy-pasta spam

### ISSUE THREAD

**Issue by DaveYognaught** [TimIsOverpowered/MOONMOON-Frontend#4]
I've noticed this a lot in the vods recently, especially during the great Helper Purges of 2023 in SMM2.

Whenever chat is a little excited and spamming particularly large pargraphs worth of machine gun fire into the elpless elping crowds, the message size is tricking the chat replay into thinking the user scrolled up but it's literally just a massive fucking message is still in focus or something along those lines I don't know. So i'm having to scroll over and unpause chat fairly often. At least during this SMM2 meta at the moment. 

So I don't know if you want to increase tolerance or detect user input another method or whatever else you may think. Shruge 

Thanks. :) 

Example if needed:

https://moon2.tv/youtube/1793826385
20:18 of part 2.

**Comment by TimIsOverpowered** [comment]
https://github.com/TimIsOverpowered/MOONMOON-Frontend/commit/2b7d628d46f652b4665428a2ce218c1356dffb7e
