### ISSUE TITLE
Missing Download button

### ISSUE THREAD

**Issue by PoopBoyo** [TimIsOverpowered/MOONMOON-Frontend#8]
The download button is missing from 8/11/2023 to now.

Before:
![before](https://github.com/TimIsOverpowered/MOONMOON-Frontend/assets/144806268/6207e132-d7c9-403b-be1c-e510f28c030c)

Now:
![now](https://github.com/TimIsOverpowered/MOONMOON-Frontend/assets/144806268/ffe26f59-8eb8-4114-8a38-bf52737ddda2)

**Comment by TimIsOverpowered** [comment]
GDrive is not supported any longer as they have removed unlimited storage.
